### ISSUE TITLE
potential use case?

### ISSUE THREAD

**Issue by paulperegud** [gootik/rebar_cmd#14]
Potential use-case is not clear from README and not clear for me right now.

Care to add some examples?

**Comment by gootik** [comment]
Hi Paul, 
Yeah for sure. So the main motive behind this is to unify the way my project is invoking commonly used commands. I think it is very common for dev to wrap rebar commands in a Makefile and add extra functionality like clean up of project, running docker containers, etc. in the Makefile. 
Using this plugin, we can do all of that using rebar, and have rebar be the build tool all around.

I'll update the README with more examples, but a very good example is when we want to make using docker commands easier:

```
{start, "docker-compose up -d"}
{stop, "docker-compose rm -f"}
```

**Comment by bigodines** [comment]
updated docs.

tnx
