### ISSUE TITLE
Use os:cmd instead of Erlang ports

### ISSUE THREAD

**Issue by gootik** [gootik/rebar_cmd#22]
os:cmd handles many edge cases and in general is better.

**Comment by gootik** [comment]
Would also fix #16

**Comment by paulo-ferraz-oliveira** [comment]
I don't think the current implementation supports it, but I'd like to see commands expressed so:
```erlang
{check, ["make xref", "make dialyzer"]} % list of strings
```
and also
```erlang
{test, "make test"} % single string
```
in which case, a "quickfix" for #16 would be to use the new syntax (list of string).

**Comment by gootik** [comment]
@paulo-ferraz-oliveira I like the first suggestion. but I still think we should change to os:cmd.

**Comment by paulo-ferraz-oliveira** [comment]
> I still think we should change to os:cmd.

Oh, I was intending on using it 😄. When I wrote "I don't think the current implementation supports it" I was referring to what I was going to expose below it.

So:
1. use `os:cmd`,
2. implement a command syntax like:
```erlang
{check, ["make xref", "make dialyzer"]} % list of strings
```
while not breaking backward compatibility.

**Comment by gootik** [comment]
yeah that's perfect

**Comment by paulo-ferraz-oliveira** [comment]
With the previous implementation you could always recover the return code from the command, which won't be possible with `os:cmd` it seems.

Is this acceptable?

**Comment by paulo-ferraz-oliveira** [comment]
Reading ref.: http://www.arv.io/articles/calling-shell-from-erlang.

**Comment by paulo-ferraz-oliveira** [comment]
I ended up not implementing this syntax
```erlang
{check, ["make xref", "make dialyzer"]} % list of strings
```
as several questions arose that would make its UX difficult.
If its asked for, in the future, we could consider it.
