### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [gootik/rebar_cmd#27]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

**Comment by gootik** [comment]
yeah that makes complete sense. I should probably do that for all of my repos.
Would you be interested in doing for rebar_cmd? I can add you as a co-owner and you would have direct access to master :D

**Comment by paulo-ferraz-oliveira** [comment]
I'll do it for `rebar_cmd`. No need for co-ownership, though, since it's not strictly necessary, but I appreciate the vote of confidence. Expect this to land today.
